# Generated by Django 3.2.7 on 2021-10-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_representante_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
