# Generated by Django 3.2.7 on 2021-10-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_junta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='imagenes_registro')),
            ],
        ),
        migrations.RemoveField(
            model_name='representante',
            name='imagen',
        ),
    ]
