# Generated by Django 3.2.7 on 2021-10-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='imagen',
        ),
        migrations.AddField(
            model_name='junta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
