# Generated by Django 3.2.7 on 2021-10-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211005_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='image',
            field=models.ImageField(upload_to='media\\imagenes_registro'),
        ),
    ]
